// flow-typed signature: eba3393a81d771b7d2e0b588d5d3a35b
// flow-typed version: <<STUB>>/sanitize.css_v^8.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
