// flow-typed signature: f8aecfad93d824b857447ade8fb73d76
// flow-typed version: <<STUB>>/webpack-dev-server-qr-code_v^1.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server-qr-code'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server-qr-code' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server-qr-code/src/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server-qr-code/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server-qr-code/index' {
  declare module.exports: $Exports<'webpack-dev-server-qr-code'>;
}
declare module 'webpack-dev-server-qr-code/index.js' {
  declare module.exports: $Exports<'webpack-dev-server-qr-code'>;
}
declare module 'webpack-dev-server-qr-code/src/index.js' {
  declare module.exports: $Exports<'webpack-dev-server-qr-code/src/index'>;
}
declare module 'webpack-dev-server-qr-code/src/index.test.js' {
  declare module.exports: $Exports<'webpack-dev-server-qr-code/src/index.test'>;
}
